### PR TITLE
Input parsing

### PR DESCRIPTION
**Pull request by eldang**
This isn't a very useful project yet!  But this is a chunk of work that makes sense together.  So far:

1. Opens an input file
2. Parses all the coordinates in it, keeping them organised as polylines
3. Identifies the bounding box for all of those lines

To do next:

4. I need to come up with a metadata specification for elevation data sources, to include their bounding boxes (to choose which data source to use for a given input file) and the date the source was last checked (to facilitate keeping local copies up to date)
5. Pick a data source based on the bbox
6. Start processing coordinates!
7. Save output

### CODE REVIEW

**Comment by eldang** [comment]
@dabreegster It's your call whether we:

a) Apply a strict code review protocol, i.e. I don't merge anything without your sign-off.
b) Treat PRs are more FYI, i.e. I'll always request your review but won't necessarily wait to hear back before moving on.
c) Stop tagging you in PRs because it's too much noise.

I'm defaulting to (b) for now.  I'll probably merge this tomorrow morning if you don't object, and I'm going to start the design work for handling data sources today, without waiting to hear back.

**Comment by eldang** [comment]
Heh, actually I can't formally request review until/unless you accept the invitation to collaborate.  I suppose that makes sense because it could be use to spam or harass people (deluge of PRs for changes that just add "bla bla bla {person} is a {slur}" comments, etc).

**Comment by dabreegster** [comment]
(b) sounds good to me.

Everything here seems fine so far. I've never seen Python's new gradual types in a real project before, so I'm excited to learn a bit by watching this evolve!

**Comment by eldang** [comment]
Haha, the type hints are a bit of a shiny-and-new thing for me too, just picked up from a collaborator over the past couple of months.

**Review by dabreegster — APPROVED** [review]

**Comment by eldang** [comment]
@all-contributors please add @eldang for bug, code, doc, projectManagement, review

**Pull request merged**
